export const workplaces = [
  {
    company: "The Stellar Collective",
    role: "Senior Frontend Developer Consultant",
    date: "Present",
    assignments: [
      {
        company: "RCO Security / Dinbox",
        role: "Senior Frontend Developer & UI/UX Designer",
        date: "2023 - 2024",
      },
    ],
    current: true,
  },
  {
    company: "Pluck",
    role: "Co-founder",
    date: "2021 - 2024",
  },
  {
    company: "Digitalist Sweden",
    role: "Frontend Lead & Certified Scrum Master",
    date: "2018 - 2021",
  },
  {
    company: "Wunderkraut",
    role: "Frontend Lead & Certified Scrum Master",
    date: "2017 - 2018",
  },
  {
    company: "Bricco",
    role: "Fullstack Developer",
    date: "2014 - 2017",
  },
  {
    company: "River",
    role: "Internship",
    date: "2011 - 2012",
  },
]

export const toolsAndTechnologies = [
  "React",
  "React Native",
  "Preact",
  "Next.js",
  "Vue",
  "Nuxt.js",
  "Javascript",
  "Typescript",
  "HTML",
  "CSS",
  "SCSS",
  "LESS",
  "Styled Components",
  "Node.js",
  "Expo",
  "PHP",
  "Redux",
  "Zustand",
  "MySQL",
  "PostgreSQL",
  "Wordpress",
  "Drupal",
  "Strapi",
  "Sanity",
  "Supabase",
  "Firebase",
  "MongoDB",
  "GraphQL",
  "Prisma",
  "Drizzle",
  "Hono",
  "TailwindCSS",
  "Storybook",
  "Shadcn/UI",
  "Material UI",
  "Vuetify",
  "Bootstrap",
  "Git",
  "Gitlab",
  "Docker",
  "Figma",
  "Sketch",
  "Webflow",
  "Framer",
  "Framer Motion",
  "Jira",
  "Azure",
  "Notion",
  "Trello",
  "AWS",
  "VSCode",
  "Jest",
  "Playwright",
  "Cypress",
  "Vercel",
  "Netlify",
  "Auth0",
  "Clerk",
  "Auth.js",
  "MacOS",
]
